# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

import contextlib
import dataclasses
import operator
from typing import Callable, Collection, Dict, List, Literal, Optional, Self, Sequence, Tuple, TypeAlias, Union, cast

import more_itertools
import torch
from torch.fx import Node, Graph, GraphModule
from torch.fx.experimental.proxy_tensor import make_fx
from torch.nn.modules import Module

from easier.core.jit import EasierTracer
import easier.core.module as esr
from easier.core.passes.collective_initialization import collectively_initialize_and_validate
from easier.core.passes.tensor_grouping import group_tensors, get_node_tensor_group
from easier.core.runtime.jit_engine.jit_engine import get_value_runtime_info
from easier.core.runtime.metadata import Role, RuntimeTensorMeta, StructuredTensorMeta, collect_meta, set_node_meta, get_node_meta, get_runtime_metadata_from_scalar
from easier.core.passes.utils import \
    FX, EasierInterpreter, OrderedSet, SubmodNameAllocator, get_easier_objects, isinst_checker, normalize_reducer_call_into_args, \
    get_torch_func_inplace_arg, get_easier_tensors, get_attr_value, fx_normalize_function_variant_into_kwargs, tree_map, \
    normalize_selector_call_into_args
    
from easier.core.utils import EasierJitException
from easier.core.autodiff.utils import simplify_torchfunc_fx_graph

from .torch_jvp import tangent_rules, differentiabilities

class Jvp(esr.Module):
    """
    """
    def __init__(self):
        super().__init__()

        inputs: Sequence[esr.Tensor]
        outputs: Sequence[esr.Tensor]

        vector: Sequence[esr.Tensor]
        product: Sequence[esr.Tensor]
        # TODO how about tangents_in tangents_out?
    
    def forward(self):
        raise EasierJitException()


FxConst: TypeAlias = Union[int, float, str]


"""
TODO
-   Calculate connectivity between each op to a specified input/ouput,
    ops that aren't connected are not transformed to forward AD.
    -   all "sources/sinks" are in the middle of the graph.
    -   Nodes to carry dual numbers are connected to at least one input and at least one output.
    -   user-defined esr.Tensors, even not specified as input/output,
        as long as it's involved, we need to create tangent Tensor for it,
        as it might be cross-nested-module (for those not, can be totally immediate
        -- does fusion allow to write immediate vars?), but just not exposed via Jvp.
"""



@dataclasses.dataclass
class _PropStackTrace:
    """
    This is basically the call stack plus the IR offset.

    However, offsets (Nodes) are not recorded for all stackframes. Because we
    are taking the union of propagated tangent flows if a Module is called
    multiple times, only the first involvement of a Tensor in called-once
    Module makes sense.
    """
    stackframes: Sequence[esr.Module]
    current_node: Node  # a Node in the innermost Node

class TangentFlowPropCtx:
    """
    Propagation context for one Module instance.
    """
    def __init__(self, module: esr.Module, graph: Graph) -> None:
        #
        # Effectively constant data
        # =============
        # fx.Graph for the primal Module.
        # NOTE this Graph are generated by EasierTracer once and discarded,
        # only for creating the JVP Module. Only with JIT 'torch' backend will
        # the Module be traced again.
        self.graph = graph
        # All esr.Tensors accessible to this Module and its submodules.
        self.accessible_tensors: OrderedSet[esr.Tensor] = OrderedSet(
            get_easier_tensors([module])
        )

        #
        # Propagator-populated data
        # =============
        # How many times a submod instance is called, if one has been called
        # multiple times, we need to union the tangent flow on its graph.
        self.call_count: int = 0

        # The snapshot of involved primal esr.Tensors to a Module at the
        # beginning of one turn of the propagation on it:
        # - recursively including Tensors in further nested sub Modules
        # - not including Tensors not accessible from this Module and
        #   its sub Modules
        # If the snapshot doesn't change, given the static nature of EASIER
        # graphs, we don't need to propagate again.
        # NOTE the snapshot set is incremental only.
        self.primal_srcs_snapshot: OrderedSet[esr.Tensor] = OrderedSet()

        # TODO easy for output Nodes, but how about input Nodes
        self.prop_flow: Dict[Node, object] = {}

class GlobalTangentFlowPropCtx:
    """
    Propagation context for the overall propagation across the root Module
    and all nested Module instances.
    """
    def __init__(self, primal_srcs: OrderedSet[esr.Tensor]) -> None:
        #
        # Effectively constant data
        # =============
        self.initial_primal_srcs = primal_srcs

        #
        # Propagator-populated data
        # =============
        self.module_ctx: Dict[esr.Module, TangentFlowPropCtx] = {}

        # The dynamically increased set of primal esr.Tensors that are ever
        # involved in the global tangent flow.
        # NOTE this set will be added or popped, and can be less than the
        # initially specified `initial_primal_srcs`.
        self.primal_srcs = OrderedSet(primal_srcs)

        # Use tuple instead of list for its immutability, so new StackTrace
        # can safely store it without explicit copy.
        self.prop_stackframe: Tuple[esr.Module, ...] = ()

        #TODO
        # self.primal_earliest_tangent_pairing: Dict[esr.Tensor, _PropStackTrace] = {}
    
    
    @contextlib.contextmanager
    def new_prop_stackframe(self, module: esr.Module):
        self.prop_stackframe += (module,)
        yield
        self.prop_stackframe = self.prop_stackframe[:-1]


class TangentFlowPropagatorBase(EasierInterpreter):
    """
    Agnostic to forward or backward propagation of tangent flow, this base
    class provides common behavior of the propagation:
    
    -   If a nested Module instance is called / propagated-to multiple times,
        the PropagatorBase decides if the propagation result is statically
        known and skips that nested Module.
    
    -   The PropagatorBase decides if a Node is an inplace operation.
    """
    def __init__(
        self, module: esr.Module, graph: Graph,
        gctx: GlobalTangentFlowPropCtx,
        reverse: bool
    ):
        assert module in gctx.module_ctx

        super().__init__([module], [graph], reverse)
        self.module = module

        self.gctx = gctx
        self.ctx = gctx.module_ctx[module]


    
    # TODO if a esr.Tensor involved in tangent flow but is not used across
    # submodules, we don't really need a persistent tangent esr.Tensor for it.

    def run(self) -> Self:
        ctx = self.ctx
        ctx.call_count += 1

        with self.gctx.new_prop_stackframe(self.module):

            latest_primals_snapshot = ctx.primal_srcs_snapshot

            # NOTE As initial primal src Tensor may be shadowed by non-carrier
            # values, the snapshot may contain Tensors not in realtime
            # primal_srcs.
            # 
            # Likewise, realtime primal_srcs may contain new Tensors not in the
            # snapshot -- if one such new Tensor is also accessed by the Module
            # we need to propagate along the Module again.
            new_primals_snapshot = OrderedSet(
                ps
                for ps in self.gctx.primal_srcs
                if ps in ctx.accessible_tensors
            )

            if len(new_primals_snapshot - latest_primals_snapshot) > 0:
                # Enter nested propagation only when tangent sources are updated
                # on the root submodule.
                super().run()
            
            ctx.primal_srcs_snapshot = new_primals_snapshot

        return self

    def if_call_function(self, function: Callable):
        # NOTE setitem and util get_torch_func input aren't needed, the inplace should be integrated into AD rule/subproc.
        if function is operator.setitem:
            inplace_arg = self.current_node.args[0]
            assert isinstance(inplace_arg, Node)
        elif function.__name__.endswith('_'):
            inplace_arg = self.current_node.kwargs.get('input', None)
            if inplace_arg is None:
                inplace_arg = self.current_node.args[0]
        else:
            # Some operations' `out` keyword parameter is actually a tuple
            # e.g. `torch.cummax(input, dim, *, out=(values, indices))`
            inplace_arg = self.current_node.kwargs.get('out', None)

        if isinstance(inplace_arg, Sequence):
            # No more nested, and not mixing Node/None.
            assert all(map(isinst_checker(Node), inplace_arg))
        else:
            assert inplace_arg is None or isinstance(inplace_arg, Node)

        self.on_operation(inplace_arg)  # type: ignore
    
    def if_call_method(self, method_name: str):
        if method_name.endswith('_'):
            inplace_arg = self.current_node.args[0]
            assert isinstance(inplace_arg, Node)
        else:
            assert 'out' not in self.current_node.kwargs, \
                f"Tensor method {method_name} has `out` parameter" \
                " and this is not expected"
            inplace_arg = None

        self.on_operation(inplace_arg)

    
    def if_call_module(self, submod: Module):
        if isinstance(submod, esr.Module):
            """
            Given an esr.Tensor `p` both used in parent Module and submod,
            if submod ever does `p[:] = f(tangent_carrier)`, `p` propagates
            tangent into parent Module too.

            However, `p`'s tangent Tensor is only used after the submod call.
            This the same as normal attribute Tensors too.
            """
            submod_ctx = self.gctx.module_ctx[submod]
            sub_prop = self.__class__(
                submod, submod_ctx.graph, self.gctx  # type: ignore
            ).run() 
        
        else:
            if isinstance(submod, esr.Reducer):
                input, out = normalize_reducer_call_into_args(
                    *self.current_node.args, **self.current_node.kwargs
                )
                assert out is None or isinstance(out, Node)
            else:
                out = None

            self.on_operation(out)
    
    def on_operation(self, written_arg: Union[None, Node, Sequence[Node]]):
        """
        NOTE about views:
        We can only tell if the input Node is a derived view or not
        in runtime by checking the memory address of the tensor.
        (e.g. `y = x.reshape().reshape().reshape()`, it's hard to tell
        if `y` is a view of `x`)

        This difficulty is eliminated since we have `data_dependency_analysis`
        pass in the runtime, it requires explicit `clone()` calls after
        operations that create views. So we don't need to worry about views
        even in pre-`compile()` subprocedures (like `jvp()`) or AOT passess.
        
        So, we can be confident that by checking the immediate Node written
        by some operation, we can identify the Tensor instance that's written:
        -   If input Node is 'get_attr', an esr.Tensor instance is written;
        -   Otherwise, an immediate result Tensor is written;
        """
        raise NotImplementedError()


class TangentFlowForwardPropagator(TangentFlowPropagatorBase):
    """
    Forward propagate tangent flow. Initial sources of tangent flow are
    GET_ATTR Nodes for input esr.Tensors in jvp() API.

    The involved Tensors/Nodes are called "tangent carriers".

    Forward propagation has these properties:
    
    -   During propagation, initially non-source esr.Tensors may become new
        sources of tangent flow, if they are written with primal values
        carrying tangents;

        Or, they become non-sources, if they are written with primal values
        carrying no tangents.
        
        Such changes should affect all GET_ATTR Nodes and their users that are
        related to those source esr.Tensors, initial or new.
    

    And in forward propagation we don't prune those Nodes that don't eventually
    contribute to any output.
    We'll prune (intersect) results of both passes of propagation.
    """
    def __init__(self, module: esr.Module, graph: Graph, gctx: GlobalTangentFlowPropCtx):
        super().__init__(module, graph, gctx, reverse=True)

    def if_get_attr(self, submod_path: str, attr_name: str, attr_val):
        # When an esr.Tensor is just 'get_attr'-ed, it may not be regarded to
        # be paired with tangent yet. This may happen on esr.Tensors that are
        # not specified in `jvp()` arguments.
        # But in the middle of the graph, the Tensor may be written with
        # values that carry tangents.
        # At that timing, we mark the Node as tangent flow, and record the
        # Tensor to be paired with tangent, 
        ctx = self.ctx
        if attr_val in self.gctx.primal_srcs:
            ctx.prop_flow.add(self.current_node)

            # self.gctx.primal_earliest_tangent_pairing.setdefault(
            #     attr_val,
            #     _PropStackTrace(self.gctx.prop_stackframe, self.current_node)
            # )

    def _is_arg_tangent_carrier(self, arg: Node):
        if arg in self.ctx.prop_flow:
            return True
    
        if arg.op == FX.GET_ATTR:
            param: torch.Tensor = get_attr_value(self.module, arg)
            return param in self.ctx.primal_srcs  # type: ignore
        
        return False
    
    def on_operation(self, written_arg: Union[None, Node, Sequence[Node]]):
        """
        """
        args_carry_tangent = any(
            self._is_arg_tangent_carrier(arg)
            for arg in self.current_node.all_input_nodes
        )
        if args_carry_tangent:
            self.current_flow.add(self.current_node)

        if written_arg is not None:
            if written_arg.op == FX.GET_ATTR:
                attr_tensor = get_attr_value(self.module, written_arg)
                assert isinstance(attr_tensor, esr.Tensor)

                # If this write causes `attr_tensor` to become a carrier,
                # then, after this write:
                # - all GET_ATTR Nodes, `written_node` and those of `attr_tensor`'s aliases,
                #   become tangent flow Nodes;

                # Particularly, we don't add GET_ATTR Node into `current_flow`, but
                # use `primal_srcs` to check if a GET_ATTR Node is a carrier or not.
                if args_carry_tangent:
                    self.gctx.primal_srcs.add(attr_tensor)

                # TODO if we don't add written_node into current_flow, we should
                # activate check GET_ATTR in following for_node or written_node.op == GET_ATTR

                # If args carry tangent, those tangent are merged into
                # the target carrier. If `attr_tensor` is not a carrier yet,
                # make it a carrier.
                # If args do not carry tangent, particularly in the case of
                # setitem(target, args), if target is a carrier, its tangent
                # should be zero-ed out.

            else:
                if written_arg in self.current_flow:
                    1

                1
                # Write to an immediate tensor.

        
        # Because of the enforced clone-view rule, no matter this inplace Node
        # has users (user must be a `clone` call) or not, it's not a view.
        # I.e. the tangent in this moment must be cloned too.


class TangentFlowBackwardPropagator(TangentFlowPropagatorBase):
    """
    Unlike forward propagation of tangent flow, in the backward propagation,
    there aren't any tangent values propagated/pushed-forward along the Nodes,
    instead, we are marking the possible path that's meaningful for JVP.

    In such a sense, the involved Tensors/Nodes are called "tangent receivers".

    ```
    p = GET_ATTR[p]
    q = GET_ATTR[q]

    w = tan(q)
    setitem(p, :, w)  # write GET_ATTR p, backprop from here

    # mark GET_ATTR p

    v = sin(p)  # v in flow, v's arg p is GET_ATTR
    setitem(output, :, v)
    ```

    
    And in backward propagation we don't prune those Nodes that are not
    derived from any input.
    We'll prune (intersect) results of both passes of propagation.
    """
    def __init__(self, module: esr.Module, graph: Graph, ctx: GlobalTangentFlowPropCtx):
        super().__init__(module, graph, ctx, reverse=True)
    
    def _is_user_tangent_carrier(self, user: Node):
        return True

    def on_operation(self, written_arg: Optional[Node]):
        if written_arg is not None:
            # TODO is this a convention?
            assert len(self.current_node.users) == 0


        users_carry_tangent = any(
            self._is_user_tangent_carrier(user)
            for user in self.current_node.users
        )
        if users_carry_tangent:
            self.current_flow.add(self.current_node)

        if written_arg is not None:
            if written_arg.op == FX.GET_ATTR:
                attr_tensor = get_attr_value(self.module, written_arg)
                assert isinstance(attr_tensor, esr.Tensor)

                if attr_tensor in self.ctx.primal_srcs:
                    self.current_flow.add(self.current_node)


class JvpTransformer(EasierInterpreter):
    """
    Recursive transformation from a pair of Module/Graph for primal calculation
    to a Module/Graph for jvp.

    The recursion happens on JvpTransformer rather than `easier.jvp()`,
    the result of this is that there won't be explicit easier.Tensors to
    store tangents at the boundary of nested easier.Modules.
    """
    def __init__(
        self,
        module: esr.Module,
        jvp_module: Jvp,
        initial_tangent_tensors: Dict[esr.Tensor, esr.Tensor]
    ):
        # TODO move outside
        [module], [graph] = collectively_initialize_and_validate([module])
        [module], [graph] = group_tensors([module], [graph])


        _getattr_vals = set()
        class _SingleGetAttrValidator(EasierInterpreter):
            # torch.fx would likely deduplicate GET_ATTR for multi-aliases
            # attribute Tensor, but the correctness of AD explicitly relies on
            # such a property, therefore we need to validate it.
            def if_get_attr(self, submod_path: str, attr_name: str, attr_val):
                if attr_val in _getattr_vals:
                    raise NotImplementedError(
                        "EASIER currently does not accept that in FX Graph"
                        " two 'get_attr' Nodes point to the same instance"
                    )
                _getattr_vals.add(attr_val)
        _SingleGetAttrValidator([module], [graph]).run()


        super().__init__([module], [graph])

        self.jvp_module = jvp_module
        self.initial_tangent_tensors = initial_tangent_tensors

        self.jvp_graph = Graph()
        self.nodemap_raw2primal: Dict[Node, Node] = {}
        self.nodemap_raw2tangent: Dict[Node, Node] = {}

        # Not only supporting submod, any kinds of attributes are OK.
        self.tangent_name_allocator = SubmodNameAllocator('tangent')



    def _fake_eval_meta_ctor(self, shape, dtype):
        # Special function needed by get_value_runtime_info, to provide
        # Role in TensorMeta.
        ng = get_node_tensor_group(self.current_node)
        if ng is None:
            role = Role.REPLICATED

        else:
            role = Role.DISTRIBUTED
            shape = (1000,) + shape[1:]

        return RuntimeTensorMeta(role, shape, dtype)
    
    def _create_zero_val(
        self, raw_node_arg: Union[Node, Sequence[Node]]
    ) -> Union[torch.Tensor, Sequence[torch.Tensor]]:
        """
        `raw_node_arg` is an argument of raw Graph Node, it may be a nested
        structure,
        e.g. torch.cat Node may have `args[0] == [x1, x2, x3]`.
        
        The result may also be a nested structure of many zero tensors.
        """
        def _make(x):
            assert isinstance(x, Node), \
                "In a list, Node and scalar are not expected to be mixed"

            meta = get_node_meta(x)
            assert isinstance(meta, RuntimeTensorMeta), \
                "Value of arg Node cannot be nested structure"

            return torch.zeros(meta.shape, dtype=meta.dtype)

        return tree_map(raw_node_arg, _make)
    

    def if_get_attr(self, submod_path: str, attr_name: str, attr_val) -> None:
        runtime_meta = get_value_runtime_info(
            self.current_node, attr_val, self._fake_eval_meta_ctor
        )
        set_node_meta(self.current_node, runtime_meta)

        primal_node = self.jvp_graph.node_copy(self.current_node)
        self.nodemap_raw2primal[self.current_node] = primal_node

        if attr_val in self.initial_tangent_tensors:
            # Simplified: it's unlikely the same primal tensor has GET_ATTR
            # Nodes multiple times, therefore it's OK to inject GET_ATTR Nodes
            # for tangent each time.
            tangent_tensor = self.initial_tangent_tensors[attr_val]
            tangent_name = self.tangent_name_allocator.alloc_name(self.jvp_module, attr_name)
            setattr(self.jvp_module, tangent_name, tangent_tensor)

            # Inject tangent node
            tangent_node = self.jvp_graph.get_attr(tangent_name)

            # Bind primal-tangent
            self.nodemap_raw2tangent[self.current_node] = tangent_node



    def if_call_function(self, function: Callable) -> None:
        if self._try_handle_inplace(function):
            return
        
        self._handle_noninplace(function)
        
    def _try_handle_inplace(self, function: Callable) -> bool:
        """
        Basically we treat all inplace ops as "non-inplace ops plus setitem".

        An important extra property for inplace ops is that the target Node,
        esr.Tensor instance or immediately result, may not be bound with
        tangent initially.
        It's at this inplace Node does the target starts to have tangent.
        """
        if function is operator.setitem:
            inplace_arg = self.current_node.args[0]

            # Actually should be `identify` (no such op!).
            # Let's handle setitem specially.
            noninplace_op = operator.setitem

        elif function.__name__.endswith('_'):
            inplace_arg = self.current_node.kwargs.get('input', None)
            if inplace_arg is None:
                inplace_arg = self.current_node.args[0]

            noninplace_op = getattr(
                function.__module__, function.__name__[:-1]
            )

        else:
            inplace_arg = self.current_node.kwargs.get('out', None)

            noninplace_op = function
        

        # If not an inplace op, back to continue with JVP transformation
        if inplace_arg is None:
            return False

        
        # Some operations' `out` keyword parameter is actually a tuple
        # e.g. `torch.cummax(input, dim, *, out=(values, indices))`
        if not isinstance(inplace_arg, Node):
            raise NotImplementedError(
                "Some aten ops have multiple out args, in their Python APIs,"
                " the `out` param is a tuple."
                f" EASIER does not support it yet:\n{self.current_node}"
            )

        self._handle_noninplace(noninplace_op)

        return True
    
    def _handle_noninplace(self, function: Callable) -> Tuple[Node, Optional[Node]]:
        if function in tangent_rules:
            raise NotImplementedError()
        
        # operator.xxx only appears in non-inplace CALL_FUNCTION Nodes.
        if getattr(operator, function.__name__, None) is function:
            function = getattr(torch, function.__name__)

        #
        # Handle using torch.func.jvp and tracing.
        # This is not purely symbolic, must have proper shapes to work with.
        #

        if function not in differentiabilities:
            raise NotImplementedError(
                f"Differentiation for operator {function} is not registered"
            )
        

        # TODO for a multi-out op, its Python API has a tuple-typed `out` param
        # but its `aten` API has explicit kwarg like `values=x, indices=y`.
        # When `aten` APIs appear in higher-order AD scenario, we need AD
        # registry to cover both PyTorch Python and aten APIs.
        #
        # When handling inplace op as its noninplace version, the Node may have
        # a `out` param (and always named as `out`).
        # Remove this `out` kwarg to let FX normalization below focus on the
        # noninplace version of the op.
        noninplace_kwargs = dict(self.current_node.kwargs)
        noninplace_kwargs.pop('out', None)

        # keys are strs, values are FX arguments, of RAW Graph
        raw_node_kwargs = fx_normalize_function_variant_into_kwargs(
            function, self.current_node.args, noninplace_kwargs
        )  # type: ignore
        dfbs = differentiabilities[function]
        for dfb in dfbs:
            if dfb.all_param_names() == set(raw_node_kwargs.keys()):
                break
        else:
            assert False, \
                "Failed to resolve overloading:" \
                f" with Differentiabilities {dfbs}, get {raw_node_kwargs}"
        
        # If a diffable param happens to carry tangent
        # -- tangent on non-diffable param is not counted.
        #
        # Also, in this noninplace handler we DO NOT count tangent appearance
        # on inplace target. This is handled by the inplace handler.
        tangent_appear_flag: List[bool] = []

        for diff_param in dfb.diffable_params:
            diff_param: str
            raw_node_diff_arg = raw_node_kwargs[diff_param]
            if isinstance(raw_node_diff_arg, (Node, Sequence)):
                arg_flags = collect_meta(
                    raw_node_diff_arg,
                    self.nodemap_raw2tangent.__contains__,
                    leaf_type=Node
                )
                tangent_appear_flag.extend(arg_flags)
        

        if not any(tangent_appear_flag):
            #
            # No tangent computation for the noninplace part.
            #
            jvp_primal_node = self.jvp_graph.node_copy(
                self.current_node, arg_transform=self.nodemap_raw2primal.__getitem__
            )
            self.nodemap_raw2primal[self.current_node] = jvp_primal_node
            return (jvp_primal_node, None)


        #
        # Differentiable parts of raw inputs, primal inputs, tangent inputs
        #

        # Some diffable parameters are given as literals e.g. "add(x, 3)"
        # and we need to convert them to replicated tensors to simplify
        # the generated tangent sub-Graph.
        jvp_diff_primal_vals: \
            Dict[str, Union[torch.Tensor, Sequence[torch.Tensor]]] = {}
        jvp_tangent_vals: \
            Dict[str, Union[torch.Tensor, Sequence[torch.Tensor]]] = {}

        input_primal_nodes: Dict[str, Union[FxConst, Node, Sequence[Node]]] = {}
        input_tangent_nodes: Dict[str, Union[Node, Sequence[Node]]] = {}

        for diff_param in dfb.diffable_params:
            diff_param: str
            raw_node_diff_arg = raw_node_kwargs[diff_param]

            # e.g. cat([A, B, C])  -> jvp(lambda seq: cat(*seq), [A, B, C])
            # so for param name of op, it's still mapped to a tuple.
            assert not isinstance(raw_node_diff_arg, Sequence), \
                "Nested input to torch.cat etc. must be bijectively flattened"

            if not isinstance(raw_node_diff_arg, (Node, Sequence)):
                # const scalars
                assert isinstance(raw_node_diff_arg, (int, float, str)), \
                    "If a differentiable parameter is not a fx.Node" \
                    " or Node list, it must be a scalar"
                
                # If diffable, literal integer is treated as float.
                # Take a small-sized float32 dtype.
                diff_argval = torch.zeros([], dtype=torch.float32)

                jvp_diff_primal_vals[diff_param] = diff_argval
                jvp_tangent_vals[diff_param] = diff_argval.clone()

                # For scalar primal input to jvp, we keep the arg scalar.
                input_primal_nodes[diff_param] = raw_node_diff_arg

                # Zero tangent for scalar
                #
                # NOTE it's safer to create replicated zero tensors, because
                # to generate JVP sub-Graph we use zero tensors (diff_argval)
                # so the sub-Graph may exploit the assumption that all input
                # tangents are tensors. And it eases our copying since all
                # elements are Nodes -- no need to inline scalars.
                # Although literal `1.0` may also work, computationally.
                input_tangent_nodes[diff_param] = self.jvp_graph.call_function(
                    torch.zeros, ([],), { 'dtype': torch.float32 }
                )
            
            else:  # Node or Node list

                # for a list-typed arg, we assume no mix of Node and scalar.
                jvp_diff_primal_vals[diff_param] = \
                    self._create_zero_val(raw_node_diff_arg)
                jvp_tangent_vals[diff_param] = \
                    self._create_zero_val(raw_node_diff_arg)

                input_primal_nodes[diff_param] = tree_map(
                    raw_node_diff_arg, self.nodemap_raw2primal.__getitem__
                )

                def _prepare_tangent_node(raw: Node) -> Node:
                    assert isinstance(raw, Node)
                    if raw in self.nodemap_raw2tangent:
                        return self.nodemap_raw2tangent[raw]
                    else:
                        # Create zero tangent
                        primal = self.nodemap_raw2primal[raw]
                        return self.jvp_graph.call_function(
                            torch.zeros_like, (primal,)
                        )
                input_tangent_nodes[diff_param] = tree_map(  # type: ignore
                    raw_node_diff_arg, _prepare_tangent_node
                )


        #
        # Non-differentiable parts of raw inputs, primal inputs
        #
        
        # TODO if a non-diffable raw-input Node is captured via closure to jvp,
        # it's represented by a sub-Graph Node e.g. GET_ATTR[tensor_constant0]
        # We need to map it back to primal Nodes.
        # TODO jvp_nondiff_env_nodes = {}

        jvp_nondiff_env_vals: Dict[str, Union[torch.Tensor, FxConst]] = {}
        for nondiff_param, default_arg in dfb.other_params:
            raw_node_nondiff_arg = raw_node_kwargs[nondiff_param]

            if isinstance(raw_node_nondiff_arg, Sequence):
                raise NotImplementedError("Nested non-differentiable arg")
                # PyTorch unlikely has this.
            
            if isinstance(raw_node_nondiff_arg, Node):
                raise NotImplementedError("Captured non-differentiable arg")
                jvp_nondiff_val = self._create_zero_val(raw_node_nondiff_arg)
            else:
                assert isinstance(raw_node_nondiff_arg, (int, float, str))
                jvp_nondiff_val = raw_node_nondiff_arg

            # TODO this takes effect even user specifies the value to be
            # explicitly None.
            # It seems ok that no common operators offer a default value
            # (especially when the argument is omitted at callsite)
            # that is not None.
            if jvp_nondiff_val is None:
                jvp_nondiff_val = default_arg
            
            jvp_nondiff_env_vals[nondiff_param] = jvp_nondiff_val

        
        # Differentiable Tensor-type parameters, must be passed via jvp()
        # API param list.
        # The names and the zero Tensors must be in the same order.
        diff_arg_names: List[str] = dfb.diffable_params
        diff_primal_vals = tuple(map(jvp_diff_primal_vals.__getitem__, diff_arg_names))
        tangent_vals = tuple(map(jvp_tangent_vals.__getitem__, diff_arg_names))

        # NOTE torch.jvp requires nested args must be flattened
        gm, y_meta = self._generate_jvp_subgraph_using_torchfunc(
            function, diff_arg_names,
            diff_primal_vals, tangent_vals, jvp_nondiff_env_vals
        )
        subg = simplify_torchfunc_fx_graph(gm.graph)

        set_node_meta(self.current_node, y_meta)

        #
        # Copy JVP sub-Graph into the resultant JVP Graph
        #

        # NOTE the torch.jvp sub-Graph copier reconstructs the flattened args
        copier = _TorchJvpSubGraphCopier(
            gm, subg, self.jvp_graph, diff_arg_names, input_primal_nodes, input_tangent_nodes
        ).run()

        assert isinstance(copier.output_primal, Node), "no multi-res support yet"
        assert isinstance(copier.output_tangent, Node), "no multi-res support yet"

        self.nodemap_raw2primal[self.current_node] = copier.output_primal
        self.nodemap_raw2tangent[self.current_node] = copier.output_tangent

        return (copier.output_primal, copier.output_tangent)
    
    def if_call_method(self, method_name: str):
        function = getattr(torch, method_name)
        kwargs = fx_normalize_function_variant_into_kwargs(function, self.current_node.args, self.current_node.kwargs)

        assert False

    def if_call_module(self, submod: Module):
        if isinstance(submod, esr.Module):
            raise NotImplementedError()
            # Nested easier.Module, must be JVP-ed.
            sub_jvp_transformer = JvpTransformer(self.root_jvp, submod).run()


        elif isinstance(submod, esr.Selector):
            input = normalize_selector_call_into_args(*self.current_node.args, **self.current_node.kwargs)

        elif isinstance(submod, esr.Reducer):
            if submod.reduce != 'sum':
                raise NotImplementedError()

            assert 'out' not in self.current_node.kwargs, "TODO"

            input, out = normalize_reducer_call_into_args(*self.current_node.args, **self.current_node.kwargs)
            assert out is None, "TODO"

        else:
            assert False, 'unreachable'

        assert isinstance(input, Node)
        imeta = get_node_meta(input)
        assert isinstance(imeta, RuntimeTensorMeta)
        ometa = self._fake_eval_meta_ctor(imeta.shape, imeta.dtype)
        set_node_meta(self.current_node, ometa)
        
        primal_node = self.jvp_graph.node_copy(self.current_node, self.nodemap_raw2primal.__getitem__)
        self.nodemap_raw2primal[self.current_node] = primal_node

        if input in self.nodemap_raw2tangent:
            tangent_node = self.jvp_graph.node_copy(self.current_node, self.nodemap_raw2tangent.__getitem__)
            self.nodemap_raw2tangent[self.current_node] = tangent_node

    def _generate_jvp_subgraph_using_torchfunc(
        self,
        function: Callable,
        diff_arg_names: List[str],
        diff_primal_vals: Tuple[Union[torch.Tensor, Sequence[torch.Tensor]], ...],
        tangent_vals: Tuple[Union[torch.Tensor, Sequence[torch.Tensor]], ...],
        other_kwargs: dict
    ) -> Tuple[GraphModule, StructuredTensorMeta]:
        """
        We need to note that torch.func.jvp API only leverage the order of
        parameters -- via `diff_arg_names: List[str]`,
        but FX normalization results in `Dict[str, Node]`.

        We need to convert between list and dict.

        An extra conversion is to **flatten** the nested arg e.g. on torch.cat,
        and the identities of the nested elements are only told by their
        positions in the nested structure.
        """

        # TODO flatten
        assert all(isinstance(val, torch.Tensor) for val in diff_primal_vals)
        assert all(isinstance(val, torch.Tensor) for val in tangent_vals)

        # Other non-differentiable parameters must NOT be passed via jvp()
        # API param list, but via function closure.

        def _primal_func(*args: torch.Tensor):
            # There preparations are not part of FX Proxy and won't be traced
            kw = {}
            for diff_arg_name, v in zip(diff_arg_names, args):
                kw[diff_arg_name] = v
            for other_arg_name, v in other_kwargs.items():
                kw[other_arg_name] = v
            
            # The core operation to let torch.func.jvp to analyze
            return function(**kw)
        
        def _jvp(
            primals: Tuple[torch.Tensor, ...],
            tangents: Tuple[torch.Tensor, ...]
        ):
            return torch.func.jvp(_primal_func, primals, tangents)
        
        # FX Graph, including make_fx, does not respect nested inputs,
        # so we need to manually flatten any nested args and maintain the
        # mapping between before/after flattening.
        gm: GraphModule = make_fx(_jvp)(diff_primal_vals, tangent_vals)
        y, jvp_res = gm(diff_primal_vals, tangent_vals)
        
        ng = get_node_tensor_group(self.current_node)
        if ng is None:
            role = Role.REPLICATED
        else:
            role = Role.DISTRIBUTED

        y_meta = get_value_runtime_info(self.current_node, y, self._fake_eval_meta_ctor)
        jvp_meta = get_value_runtime_info(self.current_node, jvp_res, self._fake_eval_meta_ctor)
        assert y_meta == jvp_meta

        # TODO return bijective position mapping
        return gm, y_meta

class _TorchJvpSubGraphCopier(EasierInterpreter):
    def __init__(
        self, subgm: GraphModule, subg: Graph, jvp_graph: Graph,
        diff_arg_names: List[str],
        jvp_input_primals: Dict[str, Union[FxConst, Node, Sequence[Node]]],
        jvp_input_tangents: Dict[str, Union[Node, Sequence[Node]]]         
    ) -> None:
        super().__init__([subgm], [subg])  # type: ignore

        self.jvp_graph = jvp_graph
        self.diff_arg_names = diff_arg_names
        self.jvp_input_primals = jvp_input_primals
        self.jvp_input_tangents = jvp_input_tangents

        self.nested_arg_bijective_pos = {}

        self.placeholder_i = 0  # totally 2*len(diff_arg_names)

        self.nodemap_subg2jvp: Dict[Node, Union[Node, int, float]] = {}

        self.output_primal: Union[Node, Sequence[Node]]
        self.output_tangent: Union[Node, Sequence[Node]]

        
    def if_placeholder(self, param_name: str):
        """
        Same as torch.func.jvp requirements, the PLACEHOLDER Nodes only differ
        in their positions and the order.
        """
        # param_name would be "primals_1" "tangents_2" (from `def _jvp` above)
        # and not usable.
        is_primal = self.placeholder_i < len(self.diff_arg_names)

        if is_primal:
            pos = self.placeholder_i
            jvp_primal = self.jvp_input_primals[self.diff_arg_names[pos]]
            self.nodemap_subg2jvp[self.current_node] = jvp_primal
        else:
            pos = self.placeholder_i - len(self.diff_arg_names)
            jvp_tangent = self.jvp_input_tangents[self.diff_arg_names[pos]]
            self.nodemap_subg2jvp[self.current_node] = jvp_tangent

        self.placeholder_i += 1
    
    def if_get_attr(self, submod_path: str, attr_name: str, attr_val):
        raise NotImplementedError(
            "Captured values, likely non-differentiable primal inputs"
        )
    
    def if_call_function(self, function):
        jvp_node = self.jvp_graph.node_copy(self.current_node, self.nodemap_subg2jvp.__getitem__)

        self.nodemap_subg2jvp[self.current_node] = jvp_node
    
    def if_output(self):
        """
        TODO When without AD, a multi-res Node stands individually, it's from
        tensor metadata level can we know it's multi-res.

        However, in torch.func.jvp sub-Graph, the primal multi-res Node will
        first be unpacked, then all primal result items are put in OUTPUT
        Node's args[0] list, making it NO LONGER an individual Node.
        When copying the sub-Graph into jvp Graph, we need to handle this.

        TODO Discard raw getitem Nodes and keep getitem Nodes in the sub-Graph.
        """
        subg_primals, subg_tangents = cast(
            Sequence[Union[Node, Sequence[Node]]], self.current_node.args[0]
        )

        convert = self.nodemap_subg2jvp.__getitem__
        self.output_primal = tree_map(subg_primals, convert)
        self.output_tangent = tree_map(subg_tangents, convert)
    
    def if_call_method(self, method_name: str):
        raise NotImplementedError(
            "It's unlikely that torch.func.jvp generates method calls"
        )
    
    def if_call_module(self, submod: Module):
        raise NotImplementedError(
            "It's unlikely that torch.func.jvp generates module calls"
        )


class LazyJvpModule(esr.Module):
    def __init__(self, primal_module: esr.Module, inputs: Sequence[esr.Tensor], outputs: Sequence[esr.Tensor]):
        super().__init__()

        self._check_dup_args(inputs, 'inputs')
        self._check_dup_args(outputs, 'outputs')

        
        # TODO the primal module may also be a placeholder JvpModule
        self.easier_primal_module: esr.Module = primal_module


        # nn.ParamList is not actually a Sequence[Tensor] because it lacks
        # __contains__.
        self.inputs: Sequence[esr.Tensor] = \
            torch.nn.ParameterList(inputs)  # type: ignore
        self.outputs: Sequence[esr.Tensor] = \
            torch.nn.ParameterList(outputs)  # type: ignore


        # TODO how about tangents_in tangents_out?
        self.vectors: Sequence[esr.Tensor] = torch.nn.ParameterList(
            self._args_zerolike(inputs, 'inputs')
                          )  # type: ignore
        self.products: Sequence[esr.Tensor] = torch.nn.ParameterList(
            self._args_zerolike(outputs, 'outputs')
        )  # type: ignore
    
    
    def _check_dup_args(self, args: Sequence[esr.Tensor], param_name: str):
        counts = {}
        for arg in args:
            counts.setdefault(arg, 0)
            counts[arg] += 1
        for arg, c in counts.items():
            if c > 1:
                pos = args.index(arg)
                raise ValueError(
                    f"The {pos}-th easier.Tensor gets specified {c} times"
                    f" in {param_name}"
                )
    
    def _args_zerolike(self, args: Sequence[esr.Tensor], param_name: str):
        for pos, arg in enumerate(args):
            if not arg.dtype.is_floating_point:
                raise ValueError(
                    f"The {pos}-th easier.Tensor does not have floating-point"
                    f" dtype in {param_name}"
                )

            yield esr.Tensor(
                esr.zeros_like(arg),
                mode=('partition' if arg.is_partition else 'replicate')
            )
    
    def forward(self):
        assert False, "not callable"


def jvp(
    module: esr.Module,
    inputs: Sequence[esr.Tensor],
    outputs: Sequence[esr.Tensor]
) -> LazyJvpModule:
    """
    Remarks:
    -   Input and output easier.Tensors are all mutable.
        Even, for example, `input[:] = f(output)`.

    -   If the same easier.Tensor is specified as both input and output,
        the tangent easier.Tensor for it will also be both included in both
        input and output tangent easier.Tensors.
    
    -   In `inputs` or `outputs`, the same easier.Tensor instance cannot be
        specified twice.
    """

    jvpm = LazyJvpModule(module, inputs, outputs)

    # TODO assign meaningful names to:
    # - Jvp.inputs, like `x` if input is InputModule.x
    # - Jvp.vector, like `tan_x`

    return jvpm