# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.




import dataclasses
import operator
from typing import Callable, Dict, List, Literal, Set, Tuple, Union

import torch

import easier as esr

@dataclasses.dataclass
class Differentiability:
    # TODO currently we assume the elements of an overloading lattice only
    # differ between parameter type Tensor/Scalar.
    # And each overloading lattice corresponds to a certain number of params.

    # The names for params that are differentiable.
    # Generally the param names are not ordered within this dataclass.
    diffable_params: List[str]

    # The second field is the default value.
    # NOTE A mandatory param without default value will still have the second
    # field be None, and will be overwritten by callsite non-None value.
    #
    # Generally the param names are not ordered within this dataclass.
    other_params: List[Tuple[str, Union[int, float, str]]] = dataclasses.field(default_factory=list)

    # TODO certain ops like aten::_to_copy has this field a function rather
    # than a constant, e.g.
    # `output_differentiability: ["!dtype || isDifferentiableType(*dtype)"]`
    output: Union[Literal[True], List[bool]] = True

    def all_param_names(self) -> Set[str]:
        # For current handling of overloading resolution, a Set[str] suffices.
        params = set()
        params.update(self.diffable_params)
        params.update(k for k, v in self.other_params)
        return params


class NonSchemaDifferentiabilitiyBase:
    1

#
# TODO before dispatch to Differentiability + torch.func.jvp,
# certain ops must be handled specifically and manually
#

tangent_rules: Dict[Callable, List[Tuple[Differentiability, Callable]]] = {}

def tangent(
    target_op: Callable,
    diff_params: List[str], other_params: List[Tuple[str, Union[int, float, str]]] = [],
    output_differentiability: Union[Literal[True], List[bool]] = True
):
    def wrapper(rule_func):
        tangent_rules.setdefault(target_op, []).append((
            Differentiability(
                diff_params, other_params, output_differentiability
            ), rule_func
        ))
    return wrapper

# @tangent(operator.setitem)
def setitem(
    self_p, index, value_p,
    value_t
):
    return value_t


def esr_sum(
    self_p, self_t
):
    return esr.sum(self_t)

# TODO add decorator on functions for these cases
# tangent_rules[torch.div] = []

def div(
    result,  # TODO needs result
    self_p, other_p,
    self_t, other_t
):
    return (self_t - other_t * result) / other_p




differentiabilities: Dict[Callable, List[Differentiability]] = {}

#
# GENERATED by tools/autodiff/gen_autodiff.py
#

differentiabilities[torch.mul] = [
    Differentiability(
        ['input', 'other']
    )
]

differentiabilities[torch.add] = [
    Differentiability(
        ['input', 'other'],
        [('alpha', 1)]
    )
]