# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#
# GENERATED by tools/autodiff/gen_autodiff.py
#

import torch

from .autodiff_rule import Differentiability, required, differentiabilities

differentiabilities[torch.mul] = [
    Differentiability(
        ['input', 'other']
    )
]

differentiabilities[torch.add] = [
    Differentiability(
        ['input', 'other'],
        [('alpha', 1)]
    )
]

differentiabilities[torch.lt] = [
    Differentiability(
        [],
        [('input', required), ('other', required), ('alpha', 1)]
    )
]

