# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.




import dataclasses
from typing import Callable, Dict, List, Literal, Set, Tuple, Union

import torch


@dataclasses.dataclass
class Differentiability:
    # TODO currently we assume the elements of an overloading lattice only
    # differ between parameter type Tensor/Scalar.
    # And each overloading lattice corresponds to a certain number of params.
    #
    # The full list of param names of one overloading of the operator
    params: List[str]

    # The names for params that are differentiable.
    # Must be a subset of `params`.
    diffable_params: List[str]

    # TODO certain ops like aten::_to_copy has this field a function rather
    # than a constant.
    output: Union[Literal[True], List[bool]] = True

    def __post_init__(self):
        assert len(set(self.diffable_params).difference(self.params)) == 0

#
# TODO before dispatch to Differentiability + torch.func.jvp,
# certain ops must be handled specifically and manually
#

tangent_rules: Dict[Callable, List[Tuple[Differentiability, Callable]]] = {}

# TODO add decorator on functions for these cases
# tangent_rules[torch.div] = []

def div(
    result,  # TODO needs result
    self_p, other_p,
    self_t, other_t
):
    return (self_t - other_t * result) / other_p




differentiabilities: Dict[Callable, List[Differentiability]] = {}

#
# GENERATED by tools/autodiff/gen_autodiff.py
#

differentiabilities[torch.mul] = [
    Differentiability(
        ['input', 'other'],
        ['input', 'other']
    )
]