# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.


from typing import Callable, TypeAlias, Union, cast

import torch
from torch.fx import Graph, Node
from torch.fx.node import BaseArgumentTypes as _FxConstBase
from torch.nn.modules import Module

from easier.core.passes.utils import FX, EasierInterpreter


# e.g. int, float, dtype, device, slice, range, etc.
FxConst: TypeAlias = Union[_FxConstBase, slice, range]


class _TorchFuncGraphSimplifer(EasierInterpreter):
    def if_call_method(self, method_name: str):
        assert False, "torch.func.jvp() should decomposite all Tensor methods"
    
    def if_call_module(self, submod: Module):
        assert False, "EASIER modules shouldn't be handled by torch.func.jvp()"
    
    def if_call_function(self, function):
        if function in [
            torch.ops.aten.alias.default
        ]:
            x = cast(Node, self.current_node.args[0])
            self.current_node.replace_all_uses_with(x)

            self.current_graph.erase_node(self.current_node)
        
        if function in [
            torch.ops.aten.is_same_size.default,
            torch.ops.aten._has_same_storage_numel.default,
        ]:
            assert len(self.current_node.users) == 0

            self.current_graph.erase_node(self.current_node)


def simplify_torchfunc_fx_graph(raw_g: Graph) -> Graph:
    """
    The Graph (both FX or TorchScript) from torch.func.jvp() will have many
    internal, annotation-only Nodes from torch.func, for EASIER AD usage
    these Nodes are not needed.


    The raw Graph are (likely) generated by tracing with forward-AD layer
    AutogradMeta::set_fw_grad in
    $PYTORCH_BASE/torch/csrc/autograd/autograd_meta.cpp

    The removed functions like is_same_size etc. above does not do any checks
    so it's safe to remove -- they are simply traced because they are
    calls on Tensors.


    To check how the raw Graph looks like we can run this codesnippet:
    ```
    import torch
    from torch.fx.experimental.proxy_tensor import make_fx

    x = torch.rand(5, 5, 5)
    p = torch.zeros(5, 5, 5)
    i = torch.zeros(5, dtype=torch.int64)

    def fun(x: torch.Tensor, p: torch.Tensor):
        return x.index_add(0, i, p)

    def myjvp(x, p, tx, tp):
        res, jvp = torch.func.jvp(fun, (x, p), (tx, tp))
        return res, jvp

    gm = make_fx(myjvp)(x, p, x.clone(), p.clone())
    print(gm.graph)
    ```
    """
    simp_g = Graph()
    out_v = simp_g.graph_copy(raw_g, {})
    simp_g.output(out_v)

    _TorchFuncGraphSimplifer([None], [simp_g]).run()  # type: ignore

    return simp_g

